version: '2'
services:
  web:
    build: .
    command: npm run start
    environment:
    - API=http://192.168.1.252:8080
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3002:3002"